// =============================================================================
// Copyright 2026 Caldera Technologies Ltd.
// Proprietary and confidential.
// Unauthorized copying or distribution is prohibited.
// =============================================================================

package resources

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	platformxe "github.com/calderax/platformxe-go"
)

var _ resource.Resource = &WebhookResource{}
var _ resource.ResourceWithConfigure = &WebhookResource{}

type WebhookResource struct {
	client *platformxe.Client
}

type WebhookResourceModel struct {
	ID       types.String `tfsdk:"id"`
	Name     types.String `tfsdk:"name"`
	URL      types.String `tfsdk:"url"`
	Events   types.List   `tfsdk:"events"`
	IsActive types.Bool   `tfsdk:"is_active"`
	Secret   types.String `tfsdk:"secret"`
}

func NewWebhooksEndpointResource() resource.Resource {
	return &WebhookResource{}
}

func (r *WebhookResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_webhooks_endpoint"
}

func (r *WebhookResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a PlatformXe webhook endpoint.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "Webhook identifier.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "Webhook display name.",
			},
			"url": schema.StringAttribute{
				Required:    true,
				Description: "Webhook delivery URL (HTTPS).",
			},
			"events": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
				Description: "List of event types to subscribe to.",
			},
			"is_active": schema.BoolAttribute{
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(true),
				Description: "Whether the webhook is active. Defaults to true.",
			},
			"secret": schema.StringAttribute{
				Computed:    true,
				Sensitive:   true,
				Description: "Webhook signing secret (generated by PlatformXe).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *WebhookResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*platformxe.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", "Expected *platformxe.Client")
		return
	}
	r.client = client
}

func (r *WebhookResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan WebhookResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var events []string
	resp.Diagnostics.Append(plan.Events.ElementsAs(ctx, &events, false)...)
	if resp.Diagnostics.HasError() {
		return
	}

	input := map[string]interface{}{
		"name":     plan.Name.ValueString(),
		"url":      plan.URL.ValueString(),
		"events":   events,
		"isActive": plan.IsActive.ValueBool(),
	}

	result, err := r.client.Webhooks.Create(input)
	if err != nil {
		resp.Diagnostics.AddError("Create Webhook Failed", err.Error())
		return
	}

	if id, ok := result["id"].(string); ok {
		plan.ID = types.StringValue(id)
	}
	if secret, ok := result["secret"].(string); ok {
		plan.Secret = types.StringValue(secret)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *WebhookResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state WebhookResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	result, err := r.client.Webhooks.Get(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Read Webhook Failed", err.Error())
		return
	}

	if v, ok := result["name"].(string); ok {
		state.Name = types.StringValue(v)
	}
	if v, ok := result["url"].(string); ok {
		state.URL = types.StringValue(v)
	}
	if v, ok := result["isActive"].(bool); ok {
		state.IsActive = types.BoolValue(v)
	}

	if evts, ok := result["events"].([]interface{}); ok {
		eventVals := make([]types.String, len(evts))
		for i, e := range evts {
			if s, ok := e.(string); ok {
				eventVals[i] = types.StringValue(s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, eventVals)
		resp.Diagnostics.Append(diags...)
		state.Events = listVal
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

func (r *WebhookResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan WebhookResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var events []string
	resp.Diagnostics.Append(plan.Events.ElementsAs(ctx, &events, false)...)
	if resp.Diagnostics.HasError() {
		return
	}

	input := map[string]interface{}{
		"name":     plan.Name.ValueString(),
		"url":      plan.URL.ValueString(),
		"events":   events,
		"isActive": plan.IsActive.ValueBool(),
	}

	_, err := r.client.Webhooks.Update(plan.ID.ValueString(), input)
	if err != nil {
		resp.Diagnostics.AddError("Update Webhook Failed", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *WebhookResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state WebhookResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.Webhooks.Delete(state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Delete Webhook Failed", err.Error())
		return
	}
}
